### ISSUE TITLE
Sign COSE with certificate

### ISSUE THREAD

**Issue by senzacionale** [panzi/verify-ehc#18]
Hi,

nice code. Do you also maybe have some certificate from covid19 app that I can sign COSE headers and then test it if is valid signature?

**Comment by panzi** [comment]
For that see https://dgc.a-sit.at/ehn/ and https://github.com/ehn-dcc-development/ehn-sign-verify-python-trivial

**Comment by senzacionale** [comment]
Thank you panzi. But all this qr codes need a valid signed COSE header. If is not signed correctly you will get the message "The COVID certificate does not have a valid signature"

**Comment by panzi** [comment]
You can create codes on that demo site and use the test trust list. I think it should be the same as `--certs-from AT-TEST` or if not download the test trust list from that site and use them with `--certs-file downloaded_certs.cbor`. They are i. The right file format.-------- Originalnachricht --------Betreff: Re: [panzi/verify-ehc] Sign COSE with certificate (#18)Von: senzacionale An: panzi/verify-ehc Cc: Mathias Panzenböck ,Comment 
Thank you panzi. But all this qr codes need a valid signed COSE header. If is not signed correctly you will get the message "The COVID certificate does not have a valid signature"

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/panzi/verify-ehc/issues/18#issuecomment-919124473",
"url": "https://github.com/panzi/verify-ehc/issues/18#issuecomment-919124473",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by senzacionale** [comment]
Thank you. Then I am doing something wrong. I generate qr codes in this site "https://dgc.a-sit.at/ehn/" and then tested it with app and app always tells me "The COVID certificate does not have a valid signature".

Testing for example with this app:
https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.verifier&hl=sl&gl=US

**Comment by panzi** [comment]
No you can only verify it with my script using the test trust list if you generate a code using that site. Otherwise one would be able to fake codes, so if course that doesn't work.

**Comment by senzacionale** [comment]
I understand. Thank you.

Do you maybe know if this code is also on github (https://dgc.a-sit.at/ehn/) or any similar covid-19 QR code generation app in python?

**Comment by panzi** [comment]
There is this, which I've already linked in this thread before: https://github.com/ehn-dcc-development/ehn-sign-verify-python-trivial/blob/main/hc1_sign.py

**Comment by senzacionale** [comment]
Thank you. But I assume is not the same as this page https://dgc.a-sit.at/ehn/

**Comment by panzi** [comment]
You would need to create your own key pair, of course.

**Comment by senzacionale** [comment]
True. But this library has lots of problems. Can also not create QR code for example. Or do you maybe fix this on your own already? Thank you.

**Comment by senzacionale** [comment]
Sure let me try.

I will also add QR-code generation if someone needed

```
import qrcode

#Generate QR Code
img=qrcode.make(out)
img.save('qr.png')
```

**Comment by senzacionale** [comment]
Everything is working fine now. Thank you.  

Maybe not propriet question but do you have a valid covid19 certificate with private key to make valid signature?

**Comment by panzi** [comment]
I'm not sure what you're asking?

Do I have any X509 certificate that I use for testing? No I just use the official test data and test certificates. But it is easy to generate X509 certificates using e.g. OpenSSL.

Do I have access to secret keys that are used in production by some government? No, I don't work for any government. And if I would... what would your next question be? Are you asking for access to secrets that can be used to sign documents in the name of a government department? I hope that is not where you would want to go with this question.

**Comment by senzacionale** [comment]
Hahah yes. Test certificate for testing. But I will create new one.

**Comment by panzi** [comment]
Sorry for insinuating anything else, but there are people actually asking me how to forge QR-codes. Makes me suspicious of any question in that direction. 😆

**Comment by resultxa** [comment]
Hello there, is it possible to create a fake qr-certificate with a valid signature? Thanks

**Comment by panzi** [comment]
The only way to create a DCC/DGC/EHC with a valid signature, but fictional content is by being a morally corrupt employee of a vaccination site or similar. You will be found out, get into prison and your license revoked and cause a lot of headache to people that get their valid certificate revoked as collateral.

I'll quote one of my tweets:

> I wrote a script to verify European Health Certificates (digital green covid pass). This makes people think I will help them commit document fraud!? (Gladly it's not possible because of state of the art cryptography.) Instead from now on I'll forward these messages to the police.
